// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS3iFyh31jtFohxyeVUm8AUmTuars7f54',
    appId: '1:692931232087:web:4093cdfb35624f3d9dbe12',
    messagingSenderId: '692931232087',
    projectId: 'drillox-apps',
    authDomain: 'drillox-apps.firebaseapp.com',
    databaseURL: 'https://drillox-apps-default-rtdb.firebaseio.com',
    storageBucket: 'drillox-apps.appspot.com',
    measurementId: 'G-HSV3VKJYSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmPGax-rdAmk-ezkCIdbzvpihxIsSbYk8',
    appId: '1:692931232087:android:5a0b500183c2a2f99dbe12',
    messagingSenderId: '692931232087',
    projectId: 'drillox-apps',
    databaseURL: 'https://drillox-apps-default-rtdb.firebaseio.com',
    storageBucket: 'drillox-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaDvOjUJCDSCwzrbpDkYl_qXN_1bJm0Uk',
    appId: '1:692931232087:ios:17234274df2a2d9e9dbe12',
    messagingSenderId: '692931232087',
    projectId: 'drillox-apps',
    databaseURL: 'https://drillox-apps-default-rtdb.firebaseio.com',
    storageBucket: 'drillox-apps.appspot.com',
    iosClientId: '692931232087-u6nmlr497q6dgca6jm2oagm1emv4s0hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleChallange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaDvOjUJCDSCwzrbpDkYl_qXN_1bJm0Uk',
    appId: '1:692931232087:ios:0094100b9295cad79dbe12',
    messagingSenderId: '692931232087',
    projectId: 'drillox-apps',
    databaseURL: 'https://drillox-apps-default-rtdb.firebaseio.com',
    storageBucket: 'drillox-apps.appspot.com',
    iosClientId: '692931232087-ovp4rdq2uim6a1lcgi5kia2f6bmlhakd.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleChallange.RunnerTests',
  );
}
